### PR TITLE
Refactor GUI : page Parameters #790

### PR DESCRIPTION
**Pull request by Foudro**
Refactor of the page Parameter : 

I didn't change the current page so it still work,
the new page is accessible via : 
http://localhost:8080/Cerberus/Parameter2.jsp

I didn't add a button to access the page so there is no risk that users use it. 

What change : 

Front : 
- Bootstrap style
- All labels added in the Database and displayed from the database
- New way to edit a parameter, button edit added and modal added
- DataTables are now server-side

Back : 
- We can now get parameters with index start, number of parameters to get, order by a column, asc or desc, with search term or not (Very inspired from Application DAO)
- Changement in the updateParameter Class so it fits with the modal

I tried to respect javascript standard by trying to reproduce what was already done with the Application Page.

(and there is a little fix from a typo in global.js)

I hope it will meet your expectations,
Yours sincerely.

### CODE REVIEW

**Comment by vertigo17** [comment]
I just merged the change.
A couple of remark:
-Never change the DatabaseVersionning past SQL instructions. Allways add new SQL to the bottom of the class. This is to secure that the new SQL is executed on any installed instance of cerberus. if you change a past SQL, it will never be triggered. Please isolate the documentation changes and add them into a new SQLInstruction member.
-in the modal, Change 2 parameter values to textarea. Put description outside an input in order to display it completely. 
- Still in the modal, also disply the System for the system value.
I will chek the back office part later.
You can push directly no more need for pull requests.

**Comment by Foudro** [comment]
That's what I did at first but I wasn't sure it was the right thing to do. I'll change that.
I'm not sure but the pull request doesn't seem to update after my push, maybe because the pull request is closed.

**Comment by vertigo17** [comment]
This is additional remarks:
- When clicking on edit button we should make a new call just before opening the modal (this is to reduce the risk of modifying the value from old data that are not correct any longuer).
- Interfaces should always have javadoc initialized : IParameterSystemService
- I think we can merge the 2 entities Parameter and ParameterSystem.
 We can just add 2 more data to standard Parameter class : system1 and system1Value.
This way, all layer would be the same with potential new method in case we want to get the normal value + an additional system value at the same time.
1 Entity, 
1 Factory with 2 create method with and without system1 and system1Value 
1 DAO with the readBySystemByCriteria that should be renamed to readWithSystem1BySystemByCriteria.
  In that method, the system should be used to filter the parameters (remove the hard coded filter to '') a new parameter system1 should be used to filter the left outer join (to get the new system1 and system1Value data).
  The SQL should have alias with the 3 letter of the parameter table (par) the left outer join should point to par1 alias () alias are documented in : docs/Objects_Pages_status.ods.
  loadFromResultSet should also exist with loadWithSystem1FromResultSet in order to parse the 2 additional data
1 Service.
1 Servlet : GetParameterSystem2 --> ReadParameter
  Group allowed to modify is not Integrator but Administrator
  System parameter on servlet should be used to filter '' on the DAO. System1 parameter should replace the existing System. GUI will map the system value to System1. 
  The Update servlet need to check that user is Administrator as well (we should not rely only on GUI).

Hope this is clear enought. If not I can correct once you will do a 1st attempt ;-).

**Comment by Foudro** [comment]
I think I get most of it. I'll work on that! 

Thanks for your remarks

**Comment by Foudro** [comment]
I just sent my first try, 
What I did : 

- Stop using ParameterSystem
- Added the attributes of ParameterSystem to Parameter
- Added an other create function in the Parameter function
- Merged the two services and the two DAO 
- Added in the DAO/Service the fact we can choose the two system to take value of the parameter
- Added in the DAO/Service a function to get one Parameter only
- Changed the name of the function as you said
- Changed the name of the servlet for ReadParameter (not GetParameterSystem2 anymore)
- Group allowed to modify is Administrator
- Added the check of Administrator in ModifyParameter
- Added a call to ReadParameter when showing the modifyModal
- Changed the SQL alias
- Added some Javadoc to IParameterService

I didn't remove the old files of ParameterSystem (DAO, Service, Sevlet) because the old page still need it but the new page don't need them anymore.

**Comment by Foudro** [comment]
- Added readDistinctValuesWithSystem1ByCriteria in Service/DAO 
- Fixed some issues with research and filters
- Fix display of edit modal

**Pull request merged**
